---
service: badger-v2
frameworkVersion: '2'
useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}

  dynamodb:
    stages:
      - staging
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      default:
        sources:
          - table: ${self:custom.table.TOKEN_PRICE_DATA}
            sources: [./seed/prices.json]
          - table: ${self:custom.table.VAULT_SNAPSHOTS_DATA}
            sources: [./seed/vault-snapshots.json]
          - table: ${self:custom.table.TOKEN_INFORMATION_DATA}
            sources: [./seed/token-info.json]
          - table: ${self:custom.table.VAULT_DEFINITION_DATA}
            sources: [./seed/vault-definition.json]
          - table: ${self:custom.table.CHART_DATA}
            sources: [./seed/chart-data.json]

  serverless-offline:
    noPrependStageInUrl: true

  table:
    YIELD_SNAPSHOTS_DATA: yield-snapshots-${self:custom.stage}
    YIELD_ESTIMATES_DATA: yield-estimates-${self:custom.stage}
    YIELD_PROJECTIONS_DATA: yield-projections-${self:custom.stage}
    VAULT_SNAPSHOTS_DATA: vault-snapshots-${self:custom.stage}
    VAULT_DEFINITION_DATA: vault-definitions-${self:custom.stage}
    # revert this to vault-balances post deploy
    VAULT_BALANCES_DATA: vault-balance-${self:custom.stage}
    TOKEN_PRICE_DATA: token-prices-${self:custom.stage}
    TOKEN_INFORMATION_DATA: token-information-${self:custom.stage}
    VAULT_YIELD_DATA: vault-yield-data-${self:custom.stage}
    ACCOUNT_DATA: accounts-${self:custom.stage}
    METADATA_DATA: metadata-${self:custom.stage}
    METRICS_SNAPSHOTS_DATA: metrics-snapshots-${self:custom.stage}
    UNCLAIMED_SNAPSHOTS_DATA: unclaimed-snapshots-${self:custom.stage}
    LEADERBOARD_DATA: leaderboards-data-${self:custom.stage}
    LEADERBOARD_SUMMARY_DATA: leaderboards-summary-${self:custom.stage}
    CYCLE_ANALYTICS_DATA: rewards-${self:custom.stage}
    PROTOCOL_DATA: protocol-data-${self:custom.stage}
    CHART_DATA: chart-data-${self:custom.stage}

  merkleProofs:
    staging: 'badger-staging-merkle-proofs'
    prod: 'badger-merkle-proofs'

package:
  exclude:
    - node_modules/serverless*/**

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 2048
  stage: staging
  region: us-west-1
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
    minimumCompressionSize: 1024
  # TODO: transition to dot env serverless support
  environment:
    # rpc secrets
    ETH_RPC: ${env:ETH_RPC}
    BSC_RPC: ${env:BSC_RPC}
    MATIC_RPC: ${env:MATIC_RPC}
    ARBITRUM_RPC: ${env:ARBITRUM_RPC}
    # 3rd party API keys
    DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}
    UNISWAP: 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2'
    SUSHISWAP: 'https://api.thegraph.com/subgraphs/name/sushiswap/exchange'
    SUSHISWAP_MATIC: 'https://api.thegraph.com/subgraphs/name/sushiswap/matic-exchange'
    SUSHISWAP_ARBITRUM: 'https://api.thegraph.com/subgraphs/name/sushiswap/arbitrum-exchange'
    PANCAKESWAP: 'https://api.thegraph.com/subgraphs/name/pancakeswap/exchange'
    QUICKSWAP: 'https://api.thegraph.com/subgraphs/name/sameepsi/quickswap06'
    SWAPR: 'https://api.thegraph.com/subgraphs/name/dxgraphs/swapr-arbitrum-one-v3'
    BALANCER: 'https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2'
    # Table Defintions
    YIELD_SNAPSHOTS_DATA: ${self:custom.table.YIELD_SNAPSHOTS_DATA}
    VAULT_SNAPSHOTS_DATA: ${self:custom.table.VAULT_SNAPSHOTS_DATA}
    VAULT_DEFINITION_DATA: ${self:custom.table.VAULT_DEFINITION_DATA}
    VAULT_BALANCES_DATA: ${self:custom.table.VAULT_BALANCES_DATA}
    TOKEN_PRICE_DATA: ${self:custom.table.TOKEN_PRICE_DATA}
    TOKEN_INFORMATION_DATA: ${self:custom.table.TOKEN_INFORMATION_DATA}
    YIELD_ESTIMATES_DATA: ${self:custom.table.YIELD_ESTIMATES_DATA}
    YIELD_PROJECTIONS_DATA: ${self:custom.table.YIELD_PROJECTIONS_DATA}
    VAULT_YIELD_DATA: ${self:custom.table.VAULT_YIELD_DATA}
    ACCOUNT_DATA: ${self:custom.table.ACCOUNT_DATA}
    METADATA_DATA: ${self:custom.table.METADATA_DATA}
    METRICS_SNAPSHOTS_DATA: ${self:custom.table.METRICS_SNAPSHOTS_DATA}
    LEADERBOARD_DATA: ${self:custom.table.LEADERBOARD_DATA}
    LEADERBOARD_SUMMARY_DATA: ${self:custom.table.LEADERBOARD_SUMMARY_DATA}
    UNCLAIMED_SNAPSHOTS_DATA: ${self:custom.table.UNCLAIMED_SNAPSHOTS_DATA}
    PROTOCOL_DATA: ${self:custom.table.PROTOCOL_DATA}
    CHART_DATA: ${self:custom.table.CHART_DATA}
    # General Defintions
    REWARD_DATA: ${self:custom.merkleProofs.${self:custom.stage}}
    STAGE: ${opt:stage, self:provider.stage}

resources:
  Resources:
    accountsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.ACCOUNT_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'address'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'address'
            AttributeType: 'S'

    yieldSnapshotsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.YIELD_SNAPSHOTS_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
          - AttributeName: 'chainAddress'
            AttributeType: 'S'
        GlobalSecondaryIndexes:
          - IndexName: IndexApySnapshotsOnAddress
            KeySchema:
              - AttributeName: chainAddress
                KeyType: 'HASH'
            Projection:
              ProjectionType: ALL

    priceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.TOKEN_PRICE_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'address'
            KeyType: 'HASH'
          - AttributeName: 'updatedAt'
            KeyType: 'RANGE'
        AttributeDefinitions:
          - AttributeName: 'address'
            AttributeType: 'S'
          - AttributeName: 'updatedAt'
            AttributeType: 'N'

    tokenInfoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.TOKEN_INFORMATION_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'address'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'address'
            AttributeType: 'S'

    protocolMetricsSnapshotsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.METRICS_SNAPSHOTS_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'type'
            KeyType: 'HASH'
          - AttributeName: 'timestamp'
            KeyType: 'RANGE'
        AttributeDefinitions:
          - AttributeName: 'type'
            AttributeType: 'S'
          - AttributeName: 'timestamp'
            AttributeType: 'N'

    vaultsSnapshotsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.VAULT_SNAPSHOTS_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'

    vaultDefinitionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.VAULT_DEFINITION_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
          - AttributeName: 'chain'
            AttributeType: 'S'
          - AttributeName: 'isProduction'
            AttributeType: 'N'
        GlobalSecondaryIndexes:
          - IndexName: IndexVaultCompoundDataChain
            KeySchema:
              - AttributeName: 'chain'
                KeyType: 'HASH'
            Projection:
              ProjectionType: ALL
          - IndexName: IndexVaultCompoundDataChainIsProd
            KeySchema:
              - AttributeName: 'chain'
                KeyType: 'HASH'
              - AttributeName: 'isProduction'
                KeyType: 'RANGE'
            Projection:
              ProjectionType: ALL

    leaderboardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.LEADERBOARD_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'leaderboard'
            KeyType: 'HASH'
          - AttributeName: 'boostRank'
            KeyType: 'RANGE'
        AttributeDefinitions:
          - AttributeName: 'leaderboard'
            AttributeType: 'S'
          - AttributeName: 'boostRank'
            AttributeType: 'N'
          - AttributeName: 'address'
            AttributeType: 'S'
        GlobalSecondaryIndexes:
          - IndexName: IndexLeaderBoardRankOnAddressAndLeaderboard
            KeySchema:
              - AttributeName: 'address'
                KeyType: 'HASH'
              - AttributeName: 'leaderboard'
                KeyType: 'RANGE'
            Projection:
              ProjectionType: ALL

    leaderboardsSummaryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.LEADERBOARD_SUMMARY_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'leaderboard'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'leaderboard'
            AttributeType: 'S'

    vaultBalancesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.VAULT_BALANCES_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'

    metadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.METADATA_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'chainStartBlock'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'chainStartBlock'
            AttributeType: 'S'
          - AttributeName: 'chain'
            AttributeType: 'S'
          - AttributeName: 'startBlock'
            AttributeType: 'N'
        GlobalSecondaryIndexes:
          - IndexName: IndexMetadataChainAndStartBlock
            KeySchema:
              - AttributeName: 'chain'
                KeyType: 'HASH'
              - AttributeName: 'startBlock'
                KeyType: 'RANGE'
            Projection:
              ProjectionType: ALL

    unclaimedSnapshotsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.UNCLAIMED_SNAPSHOTS_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'chainStartBlock'
            KeyType: 'HASH'
          - AttributeName: 'address'
            KeyType: 'RANGE'
        AttributeDefinitions:
          - AttributeName: 'chainStartBlock'
            AttributeType: 'S'
          - AttributeName: 'address'
            AttributeType: 'S'
        GlobalSecondaryIndexes:
          - IndexName: IndexUnclaimedSnapshotsOnAddressAndChainStartBlock
            KeySchema:
              - AttributeName: 'address'
                KeyType: 'HASH'
              - AttributeName: 'chainStartBlock'
                KeyType: 'RANGE'
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: 'expiresAt'
          Enabled: true

    yieldEstimatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.YIELD_ESTIMATES_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'vault'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'vault'
            AttributeType: 'S'

    vaultYieldDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.VAULT_YIELD_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
          - AttributeName: 'timestamp'
            KeyType: 'RANGE'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
          - AttributeName: 'timestamp'
            AttributeType: 'N'
          - AttributeName: 'chainAddress'
            AttributeType: 'S'
        GlobalSecondaryIndexes:
          - IndexName: IndexYieldDataOnAddress
            KeySchema:
              - AttributeName: chainAddress
                KeyType: 'HASH'
              - AttributeName: 'timestamp'
                KeyType: 'RANGE'
            Projection:
              ProjectionType: ALL

    cycleAnalyticsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.CYCLE_ANALYTICS_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'networkCycle'
            KeyType: 'HASH'
          - AttributeName: 'cycle'
            KeyType: 'RANGE'
        AttributeDefinitions:
          - AttributeName: 'networkCycle'
            AttributeType: 'S'
          - AttributeName: 'cycle'
            AttributeType: 'N'
          - AttributeName: 'network'
            AttributeType: 'S'
          - AttributeName: 'endBlock'
            AttributeType: 'N'
        GlobalSecondaryIndexes:
          - IndexName: IndexRewardsOnNetworkAndEndBlock
            KeySchema:
              - AttributeName: 'network'
                KeyType: 'HASH'
              - AttributeName: 'endBlock'
                KeyType: 'RANGE'
            Projection:
              ProjectionType: ALL

    protocolData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.PROTOCOL_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'

    chartData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.CHART_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'

    yieldProjectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table.YIELD_PROJECTIONS_DATA}
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'id'
            KeyType: 'HASH'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'

functions:
  request-handler:
    handler: src/LambdaServer.handler
    timeout: 30
    memorySize: 4096
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
      - http:
          path: /
          method: any
          cors: true

  # index-apy-snapshots:
  #   handler: src/indexers/apy-snapshots-indexer.refreshApySnapshots
  #   timeout: 180
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-apy-snapshots
  #         description: 'index data for vault yields'
  #         rate: rate(15 minutes)

  index-vault-definitions:
    handler: src/indexers/vault-definition-indexer.captureVaultData
    timeout: 150
    events:
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-vault-definition
          description: 'index definitions for supported vaults'
          rate: rate(2 minutes)

  # index-vault-yield-events:
  #   handler: src/indexers/vault-harvests-indexer.updateVaultHarvests
  #   timeout: 900
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-vault-harvests
  #         description: 'index onchain harvests for all vaults'
  #         rate: rate(20 minutes)

  # index-prices:
  #   handler: src/indexers/prices-indexer.indexPrices
  #   timeout: 150
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-prices
  #         description: 'index price data for all protocol tokens'
  #         rate: rate(5 minutes)

  # index-vault-snapshots:
  #   handler: src/indexers/vault-snapshots-indexer.refreshVaultSnapshots
  #   timeout: 150
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-vault-snapshots
  #         description: 'index data for supported vaults'
  #         rate: rate(5 minutes)

  # index-yield-estimates:
  #   handler: src/indexers/yield-estimates-indexer.refreshYieldEstimates
  #   timeout: 150
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-yield-estimates
  #         description: 'index yield estimate data for supported vaults'
  #         rate: rate(30 minutes)

  # index-leaderboard:
  #   handler: src/indexers/leaderboard-indexer.indexBoostLeaderBoard
  #   timeout: 120
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-leaderboard
  #         description: 'index leaderboard data from latest badger boosts'
  #         rate: rate(5 minutes)

  # index-vault-balances:
  #   handler: src/indexers/vault-balances-indexer.refreshVaultBalances
  #   timeout: 180
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-vault-balances
  #         description: 'index vault token balances from the graph'
  #         rate: rate(5 minutes)

  # index-accounts:
  #   handler: src/indexers/accounts-indexer.refreshUserAccounts
  #   timeout: 900
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-claimables
  #         description: 'index accounts claimable from badger tree'
  #         rate: rate(2 hours)
  #         input:
  #           mode: ClaimableBalanceData

  # index-protocol-metrics-snapshots:
  #   handler: src/indexers/protocol-metric-indexer.indexProtocolMetrics
  #   timeout: 240
  #   events:
  #     - schedule:
  #         name: ${self:service}-${self:custom.stage}-index-protocol-metrics-snapshots
  #         description: 'index protocol metrics'
  #         rate: rate(1 day)
