import { Network } from '@badger-dao/sdk';
import { TOKENS } from '../../config/tokens.config';
import { PricingType } from '../../prices/enums/pricing-type.enum';
import { TokenConfig } from '../interfaces/token-config.interface';

export const maticTokensConfig: TokenConfig = {
  [TOKENS.MULTI_RENBTC]: {
    address: TOKENS.MULTI_RENBTC,
    decimals: 8,
    lookupName: 'renbtc',
    name: 'Ren Protocol BTC',
    symbol: 'renBTC',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_WBTC]: {
    address: TOKENS.MATIC_WBTC,
    decimals: 8,
    lookupName: 'wrapped-bitcoin',
    name: 'Wrapped Bitcoin',
    symbol: 'WBTC',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_USDC]: {
    address: TOKENS.MATIC_USDC,
    decimals: 6,
    lookupName: 'usd-coin',
    name: 'US Dollar Coin',
    symbol: 'USDC',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_USDT]: {
    address: TOKENS.MATIC_USDT,
    decimals: 6,
    lookupName: 'tether',
    name: 'Tether',
    symbol: 'USDT',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_DAI]: {
    address: TOKENS.MATIC_DAI,
    decimals: 18,
    lookupName: 'dai',
    name: 'Dai',
    symbol: 'DAI',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_IBBTC]: {
    address: TOKENS.MATIC_IBBTC,
    decimals: 18,
    lookupName: 'interest-bearing-bitcoin',
    name: 'ibBTC',
    symbol: 'ibBTC',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_AMWBTC]: {
    address: TOKENS.MATIC_AMWBTC,
    decimals: 8,
    lookupName: 'aave-polygon-wbtc',
    name: 'Aave WBTC',
    symbol: 'amWBTC',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_AMWETH]: {
    address: TOKENS.MATIC_AMWETH,
    decimals: 18,
    lookupName: 'aave-polygon-weth',
    name: 'Aave WETH',
    symbol: 'amWETH',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_AMDAI]: {
    address: TOKENS.MATIC_AMDAI,
    decimals: 18,
    lookupName: 'aave-polygon-dai',
    name: 'Aave DAI',
    symbol: 'amDAI',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_AMUSDC]: {
    address: TOKENS.MATIC_AMUSDC,
    decimals: 6,
    lookupName: 'aave-polygon-usdc',
    name: 'Aave USDC',
    symbol: 'amUSDC',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_AMUSDT]: {
    address: TOKENS.MATIC_AMUSDT,
    decimals: 6,
    lookupName: 'aave-polygon-usdt',
    name: 'Aave USDT',
    symbol: 'amUSDT',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_CRV]: {
    address: TOKENS.MATIC_CRV,
    decimals: 18,
    lookupName: 'curve-dao-token',
    name: 'Curve DAO Token',
    symbol: 'CRV',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_BADGER]: {
    address: TOKENS.MATIC_BADGER,
    decimals: 18,
    lookupName: 'badger-dao',
    name: 'Badger',
    symbol: 'BADGER',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_SUSHI]: {
    address: TOKENS.MATIC_SUSHI,
    decimals: 18,
    lookupName: 'sushi',
    name: 'Sushi',
    symbol: 'Sushi',
    type: PricingType.Contract,
  },
  [TOKENS.MATIC_SUSHI_IBBTC_WBTC]: {
    address: TOKENS.MATIC_SUSHI_IBBTC_WBTC,
    decimals: 18,
    lpToken: true,
    name: 'Sushiswap: ibBTC-WBTC',
    symbol: 'SLP-IBBTC-WBTC',
    type: PricingType.UniV2LP,
  },
  [TOKENS.MATIC_QUICK_USDC_WBTC]: {
    address: TOKENS.MATIC_QUICK_USDC_WBTC,
    decimals: 18,
    lpToken: true,
    name: 'Quickswap: USDC-WBTC',
    symbol: 'QLP-USDC-WBTC',
    type: PricingType.UniV2LP,
  },
  [TOKENS.MATIC_CRV_AM3CRV]: {
    address: TOKENS.MATIC_CRV_AM3CRV,
    decimals: 18,
    name: 'Curve.fi amDAI/amUSDC/amUSDT',
    symbol: 'crvAM3',
    type: PricingType.CurveLP,
  },
  [TOKENS.MATIC_CRV_AMWBTC]: {
    address: TOKENS.MATIC_CRV_AMWBTC,
    decimals: 18,
    name: 'Curve.fi amWBTC/renBTC',
    symbol: 'crvrenBTC',
    type: PricingType.CurveLP,
  },
  [TOKENS.BMATIC_SUSHI_IBBTC_WBTC]: {
    address: TOKENS.BMATIC_SUSHI_IBBTC_WBTC,
    decimals: 18,
    name: 'bSushiSwap: ibBTC-WBTC',
    symbol: 'bSLP-IBBTC-WBTC',
    type: PricingType.Vault,
    vaultToken: {
      address: TOKENS.MATIC_SUSHI_IBBTC_WBTC,
      network: Network.Polygon,
    },
  },
  [TOKENS.BMATIC_QUICK_USDC_WBTC]: {
    address: TOKENS.BMATIC_QUICK_USDC_WBTC,
    decimals: 18,
    name: 'bQuickswap: USDC-WBTC',
    symbol: 'bQLP-USDC-WBTC',
    type: PricingType.Vault,
    vaultToken: {
      address: TOKENS.MATIC_QUICK_USDC_WBTC,
      network: Network.Polygon,
    },
  },
  [TOKENS.BMATIC_CRV_AMWBTC]: {
    address: TOKENS.BMATIC_CRV_AMWBTC,
    decimals: 18,
    name: 'bCurve.fi amWBTC/renBTC',
    symbol: 'bcrvrenBTC',
    type: PricingType.Vault,
    vaultToken: {
      address: TOKENS.MATIC_CRV_AMWBTC,
      network: Network.Polygon,
    },
  },
};
