export const curvePoolAbi = [
  {
    name: 'TokenExchange',
    inputs: [
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'sold_id', type: 'uint256', indexed: false },
      { name: 'tokens_sold', type: 'uint256', indexed: false },
      { name: 'bought_id', type: 'uint256', indexed: false },
      { name: 'tokens_bought', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'AddLiquidity',
    inputs: [
      { name: 'provider', type: 'address', indexed: true },
      { name: 'token_amounts', type: 'uint256[3]', indexed: false },
      { name: 'fee', type: 'uint256', indexed: false },
      { name: 'token_supply', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RemoveLiquidity',
    inputs: [
      { name: 'provider', type: 'address', indexed: true },
      { name: 'token_amounts', type: 'uint256[3]', indexed: false },
      { name: 'token_supply', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RemoveLiquidityOne',
    inputs: [
      { name: 'provider', type: 'address', indexed: true },
      { name: 'token_amount', type: 'uint256', indexed: false },
      { name: 'coin_index', type: 'uint256', indexed: false },
      { name: 'coin_amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'CommitNewAdmin',
    inputs: [
      { name: 'deadline', type: 'uint256', indexed: true },
      { name: 'admin', type: 'address', indexed: true },
    ],
    anonymous: false,
    type: 'event',
  },
  { name: 'NewAdmin', inputs: [{ name: 'admin', type: 'address', indexed: true }], anonymous: false, type: 'event' },
  {
    name: 'CommitNewParameters',
    inputs: [
      { name: 'deadline', type: 'uint256', indexed: true },
      { name: 'admin_fee', type: 'uint256', indexed: false },
      { name: 'mid_fee', type: 'uint256', indexed: false },
      { name: 'out_fee', type: 'uint256', indexed: false },
      { name: 'fee_gamma', type: 'uint256', indexed: false },
      { name: 'price_threshold', type: 'uint256', indexed: false },
      { name: 'adjustment_step', type: 'uint256', indexed: false },
      { name: 'ma_half_time', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'NewParameters',
    inputs: [
      { name: 'admin_fee', type: 'uint256', indexed: false },
      { name: 'mid_fee', type: 'uint256', indexed: false },
      { name: 'out_fee', type: 'uint256', indexed: false },
      { name: 'fee_gamma', type: 'uint256', indexed: false },
      { name: 'price_threshold', type: 'uint256', indexed: false },
      { name: 'adjustment_step', type: 'uint256', indexed: false },
      { name: 'ma_half_time', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RampAgamma',
    inputs: [
      { name: 'initial_A', type: 'uint256', indexed: false },
      { name: 'future_A', type: 'uint256', indexed: false },
      { name: 'initial_time', type: 'uint256', indexed: false },
      { name: 'future_time', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'StopRampA',
    inputs: [
      { name: 'current_A', type: 'uint256', indexed: false },
      { name: 'current_gamma', type: 'uint256', indexed: false },
      { name: 'time', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'ClaimAdminFee',
    inputs: [
      { name: 'admin', type: 'address', indexed: true },
      { name: 'tokens', type: 'uint256', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'A', type: 'uint256' },
      { name: 'gamma', type: 'uint256' },
      { name: 'mid_fee', type: 'uint256' },
      { name: 'out_fee', type: 'uint256' },
      { name: 'price_threshold', type: 'uint256' },
      { name: 'fee_gamma', type: 'uint256' },
      { name: 'adjustment_step', type: 'uint256' },
      { name: 'admin_fee', type: 'uint256' },
      { name: 'ma_half_time', type: 'uint256' },
      { name: 'initial_prices', type: 'uint256[2]' },
    ],
    outputs: [],
  },
  { stateMutability: 'payable', type: 'fallback' },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'price_oracle',
    inputs: [{ name: 'k', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'price_scale',
    inputs: [{ name: 'k', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'last_prices',
    inputs: [{ name: 'k', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'token',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'coins',
    inputs: [{ name: 'i', type: 'uint256' }],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'A',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'gamma',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'A_precise',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'fee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'fee_calc',
    inputs: [{ name: 'xp', type: 'uint256[3]' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'get_virtual_price',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    name: 'exchange',
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'dx', type: 'uint256' },
      { name: 'min_dy', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    name: 'exchange',
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'dx', type: 'uint256' },
      { name: 'min_dy', type: 'uint256' },
      { name: 'use_eth', type: 'bool' },
    ],
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'get_dy',
    inputs: [
      { name: 'i', type: 'uint256' },
      { name: 'j', type: 'uint256' },
      { name: 'dx', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'calc_token_fee',
    inputs: [
      { name: 'amounts', type: 'uint256[3]' },
      { name: 'xp', type: 'uint256[3]' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'add_liquidity',
    inputs: [
      { name: 'amounts', type: 'uint256[3]' },
      { name: 'min_mint_amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'remove_liquidity',
    inputs: [
      { name: '_amount', type: 'uint256' },
      { name: 'min_amounts', type: 'uint256[3]' },
    ],
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'calc_token_amount',
    inputs: [
      { name: 'amounts', type: 'uint256[3]' },
      { name: 'deposit', type: 'bool' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'calc_withdraw_one_coin',
    inputs: [
      { name: 'token_amount', type: 'uint256' },
      { name: 'i', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'remove_liquidity_one_coin',
    inputs: [
      { name: 'token_amount', type: 'uint256' },
      { name: 'i', type: 'uint256' },
      { name: 'min_amount', type: 'uint256' },
    ],
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', name: 'claim_admin_fees', inputs: [], outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'ramp_A_gamma',
    inputs: [
      { name: 'future_A', type: 'uint256' },
      { name: 'future_gamma', type: 'uint256' },
      { name: 'future_time', type: 'uint256' },
    ],
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', name: 'stop_ramp_A_gamma', inputs: [], outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'commit_new_parameters',
    inputs: [
      { name: '_new_mid_fee', type: 'uint256' },
      { name: '_new_out_fee', type: 'uint256' },
      { name: '_new_admin_fee', type: 'uint256' },
      { name: '_new_fee_gamma', type: 'uint256' },
      { name: '_new_price_threshold', type: 'uint256' },
      { name: '_new_adjustment_step', type: 'uint256' },
      { name: '_new_ma_half_time', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'apply_new_parameters',
    inputs: [],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'revert_new_parameters',
    inputs: [],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'commit_transfer_ownership',
    inputs: [{ name: '_owner', type: 'address' }],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'apply_transfer_ownership',
    inputs: [],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'revert_transfer_ownership',
    inputs: [],
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', name: 'kill_me', inputs: [], outputs: [] },
  { stateMutability: 'nonpayable', type: 'function', name: 'unkill_me', inputs: [], outputs: [] },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'set_admin_fee_receiver',
    inputs: [{ name: '_admin_fee_receiver', type: 'address' }],
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'last_prices_timestamp',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'initial_A_gamma',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_A_gamma',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'initial_A_gamma_time',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_A_gamma_time',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'price_threshold',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_price_threshoold',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'fee_gamma',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_fee_gamma',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'adjustment_step',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_adjustment_step',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'ma_half_time',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_ma_half_time',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'mid_fee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'out_fee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'admin_fee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_mid_fee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_out_fee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_admin_fee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'balances',
    inputs: [{ name: 'arg0', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'D',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'future_owner',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'xcp_profit',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'xcp_profit_a',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'virtual_price',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'is_killed',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'kill_deadline',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'transfer_ownership_deadline',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'admin_actions_deadline',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'admin_fee_receiver',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
];
export const oldCurvePoolAbi = [
  {
    name: 'TokenExchange',
    inputs: [
      { type: 'address', name: 'buyer', indexed: true },
      { type: 'int128', name: 'sold_id', indexed: false },
      { type: 'uint256', name: 'tokens_sold', indexed: false },
      { type: 'int128', name: 'bought_id', indexed: false },
      { type: 'uint256', name: 'tokens_bought', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'AddLiquidity',
    inputs: [
      { type: 'address', name: 'provider', indexed: true },
      { type: 'uint256[3]', name: 'token_amounts', indexed: false },
      { type: 'uint256[3]', name: 'fees', indexed: false },
      { type: 'uint256', name: 'invariant', indexed: false },
      { type: 'uint256', name: 'token_supply', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RemoveLiquidity',
    inputs: [
      { type: 'address', name: 'provider', indexed: true },
      { type: 'uint256[3]', name: 'token_amounts', indexed: false },
      { type: 'uint256[3]', name: 'fees', indexed: false },
      { type: 'uint256', name: 'token_supply', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RemoveLiquidityOne',
    inputs: [
      { type: 'address', name: 'provider', indexed: true },
      { type: 'uint256', name: 'token_amount', indexed: false },
      { type: 'uint256', name: 'coin_amount', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RemoveLiquidityImbalance',
    inputs: [
      { type: 'address', name: 'provider', indexed: true },
      { type: 'uint256[3]', name: 'token_amounts', indexed: false },
      { type: 'uint256[3]', name: 'fees', indexed: false },
      { type: 'uint256', name: 'invariant', indexed: false },
      { type: 'uint256', name: 'token_supply', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'CommitNewAdmin',
    inputs: [
      { type: 'uint256', name: 'deadline', indexed: true, unit: 'sec' },
      { type: 'address', name: 'admin', indexed: true },
    ],
    anonymous: false,
    type: 'event',
  },
  { name: 'NewAdmin', inputs: [{ type: 'address', name: 'admin', indexed: true }], anonymous: false, type: 'event' },
  {
    name: 'CommitNewFee',
    inputs: [
      { type: 'uint256', name: 'deadline', indexed: true, unit: 'sec' },
      { type: 'uint256', name: 'fee', indexed: false },
      { type: 'uint256', name: 'admin_fee', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'NewFee',
    inputs: [
      { type: 'uint256', name: 'fee', indexed: false },
      { type: 'uint256', name: 'admin_fee', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RampA',
    inputs: [
      { type: 'uint256', name: 'old_A', indexed: false },
      { type: 'uint256', name: 'new_A', indexed: false },
      { type: 'uint256', name: 'initial_time', indexed: false, unit: 'sec' },
      { type: 'uint256', name: 'future_time', indexed: false, unit: 'sec' },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'StopRampA',
    inputs: [
      { type: 'uint256', name: 'A', indexed: false },
      { type: 'uint256', name: 't', indexed: false, unit: 'sec' },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    outputs: [],
    inputs: [
      { type: 'address[3]', name: '_coins' },
      { type: 'address', name: '_pool_token' },
      { type: 'uint256', name: '_A' },
      { type: 'uint256', name: '_fee' },
    ],
    constant: false,
    payable: false,
    type: 'constructor',
  },
  { name: 'A', outputs: [{ type: 'uint256', name: '' }], inputs: [], constant: true, payable: false, type: 'function' },
  {
    name: 'get_virtual_price',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'calc_token_amount',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [
      { type: 'uint256[3]', name: 'amounts' },
      { type: 'bool', name: 'deposit' },
    ],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'add_liquidity',
    outputs: [],
    inputs: [
      { type: 'uint256[3]', name: 'amounts' },
      { type: 'uint256', name: 'min_mint_amount' },
    ],
    constant: false,
    payable: false,
    type: 'function',
  },
  {
    name: 'get_dy',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [
      { type: 'int128', name: 'i' },
      { type: 'int128', name: 'j' },
      { type: 'uint256', name: 'dx' },
    ],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'get_dy_underlying',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [
      { type: 'int128', name: 'i' },
      { type: 'int128', name: 'j' },
      { type: 'uint256', name: 'dx' },
    ],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'exchange',
    outputs: [],
    inputs: [
      { type: 'int128', name: 'i' },
      { type: 'int128', name: 'j' },
      { type: 'uint256', name: 'dx' },
      { type: 'uint256', name: 'min_dy' },
    ],
    constant: false,
    payable: false,
    type: 'function',
  },
  {
    name: 'remove_liquidity',
    outputs: [],
    inputs: [
      { type: 'uint256', name: '_amount' },
      { type: 'uint256[3]', name: 'min_amounts' },
    ],
    constant: false,
    payable: false,
    type: 'function',
  },
  {
    name: 'remove_liquidity_imbalance',
    outputs: [],
    inputs: [
      { type: 'uint256[3]', name: 'amounts' },
      { type: 'uint256', name: 'max_burn_amount' },
    ],
    constant: false,
    payable: false,
    type: 'function',
  },
  {
    name: 'calc_withdraw_one_coin',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [
      { type: 'uint256', name: '_token_amount' },
      { type: 'int128', name: 'i' },
    ],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'remove_liquidity_one_coin',
    outputs: [],
    inputs: [
      { type: 'uint256', name: '_token_amount' },
      { type: 'int128', name: 'i' },
      { type: 'uint256', name: 'min_amount' },
    ],
    constant: false,
    payable: false,
    type: 'function',
  },
  {
    name: 'ramp_A',
    outputs: [],
    inputs: [
      { type: 'uint256', name: '_future_A' },
      { type: 'uint256', unit: 'sec', name: '_future_time' },
    ],
    constant: false,
    payable: false,
    type: 'function',
  },
  { name: 'stop_ramp_A', outputs: [], inputs: [], constant: false, payable: false, type: 'function' },
  {
    name: 'commit_new_fee',
    outputs: [],
    inputs: [
      { type: 'uint256', name: 'new_fee' },
      { type: 'uint256', name: 'new_admin_fee' },
    ],
    constant: false,
    payable: false,
    type: 'function',
  },
  { name: 'apply_new_fee', outputs: [], inputs: [], constant: false, payable: false, type: 'function' },
  { name: 'revert_new_parameters', outputs: [], inputs: [], constant: false, payable: false, type: 'function' },
  {
    name: 'commit_transfer_ownership',
    outputs: [],
    inputs: [{ type: 'address', name: '_owner' }],
    constant: false,
    payable: false,
    type: 'function',
  },
  { name: 'apply_transfer_ownership', outputs: [], inputs: [], constant: false, payable: false, type: 'function' },
  { name: 'revert_transfer_ownership', outputs: [], inputs: [], constant: false, payable: false, type: 'function' },
  { name: 'withdraw_admin_fees', outputs: [], inputs: [], constant: false, payable: false, type: 'function' },
  { name: 'kill_me', outputs: [], inputs: [], constant: false, payable: false, type: 'function' },
  { name: 'unkill_me', outputs: [], inputs: [], constant: false, payable: false, type: 'function' },
  {
    name: 'coins',
    outputs: [{ type: 'address', name: '' }],
    inputs: [{ type: 'int128', name: 'arg0' }],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'balances',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [{ type: 'int128', name: 'arg0' }],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'fee',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'admin_fee',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'owner',
    outputs: [{ type: 'address', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'initial_A',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'future_A',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'initial_A_time',
    outputs: [{ type: 'uint256', unit: 'sec', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'future_A_time',
    outputs: [{ type: 'uint256', unit: 'sec', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'admin_actions_deadline',
    outputs: [{ type: 'uint256', unit: 'sec', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'transfer_ownership_deadline',
    outputs: [{ type: 'uint256', unit: 'sec', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'future_fee',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'future_admin_fee',
    outputs: [{ type: 'uint256', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
  {
    name: 'future_owner',
    outputs: [{ type: 'address', name: '' }],
    inputs: [],
    constant: true,
    payable: false,
    type: 'function',
  },
];
