/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { CurvePool, CurvePoolInterface } from "../CurvePool";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        type: "int128",
        name: "arg0",
      },
    ],
    name: "coins",
    outputs: [
      {
        type: "address",
        name: "",
      },
    ],
    payable: false,
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        type: "int128",
        name: "arg0",
      },
    ],
    name: "balances",
    outputs: [
      {
        type: "uint256",
        name: "",
      },
    ],
    payable: false,
    type: "function",
  },
];

export class CurvePool__factory {
  static readonly abi = _abi;
  static createInterface(): CurvePoolInterface {
    return new utils.Interface(_abi) as CurvePoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CurvePool {
    return new Contract(address, _abi, signerOrProvider) as CurvePool;
  }
}
