/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

<<<<<<< HEAD
import { Contract, Signer, utils } from 'ethers';
import { Provider } from '@ethersproject/providers';
import type { EmissionControl, EmissionControlInterface } from '../EmissionControl';
=======
import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  EmissionControl,
  EmissionControlInterface,
} from "../EmissionControl";
>>>>>>> c15f0091 (chore: update update)

const _abi = [
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '_vault',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
=======
        internalType: "address",
        name: "_vault",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
<<<<<<< HEAD
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
=======
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
<<<<<<< HEAD
        internalType: 'address',
        name: '_vault',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: '_weight',
        type: 'uint256',
      },
    ],
    name: 'TokenBoostedEmissionChanged',
    type: 'event',
=======
        internalType: "address",
        name: "_vault",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_weight",
        type: "uint256",
      },
    ],
    name: "TokenBoostedEmissionChanged",
    type: "event",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
<<<<<<< HEAD
        internalType: 'address',
        name: '_token',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'uint256',
        name: '_weight',
        type: 'uint256',
      },
    ],
    name: 'TokenWeightChanged',
    type: 'event',
  },
  {
    inputs: [],
    name: 'MAX_BPS',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
=======
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_weight",
        type: "uint256",
      },
    ],
    name: "TokenWeightChanged",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '_manager',
        type: 'address',
      },
    ],
    name: 'addManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
=======
        internalType: "address",
        name: "_manager",
        type: "address",
      },
    ],
    name: "addManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'boostedEmissionRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
=======
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "boostedEmissionRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'manager',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
=======
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "manager",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '_vault',
        type: 'address',
      },
    ],
    name: 'proRataEmissionRate',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
=======
        internalType: "address",
        name: "_vault",
        type: "address",
      },
    ],
    name: "proRataEmissionRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '_manager',
        type: 'address',
      },
    ],
    name: 'removeManager',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
=======
        internalType: "address",
        name: "_manager",
        type: "address",
      },
    ],
    name: "removeManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '_vault',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_weight',
        type: 'uint256',
      },
    ],
    name: 'setBoostedEmission',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
=======
        internalType: "address",
        name: "_vault",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_weight",
        type: "uint256",
      },
    ],
    name: "setBoostedEmission",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '_token',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_weight',
        type: 'uint256',
      },
    ],
    name: 'setTokenWeight',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
=======
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_weight",
        type: "uint256",
      },
    ],
    name: "setTokenWeight",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'tokenWeight',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
=======
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "tokenWeight",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
  {
    inputs: [
      {
<<<<<<< HEAD
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
=======
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
>>>>>>> c15f0091 (chore: update update)
  },
];

export class EmissionControl__factory {
  static readonly abi = _abi;
  static createInterface(): EmissionControlInterface {
    return new utils.Interface(_abi) as EmissionControlInterface;
  }
<<<<<<< HEAD
  static connect(address: string, signerOrProvider: Signer | Provider): EmissionControl {
=======
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EmissionControl {
>>>>>>> c15f0091 (chore: update update)
    return new Contract(address, _abi, signerOrProvider) as EmissionControl;
  }
}
