import { SwaggerSettings } from '@tsed/swagger';
export declare const ONE_MINUTE_SECONDS = 60;
export declare const ONE_DAY_SECONDS: number;
export declare const ONE_WEEK_SECONDS: number;
export declare const ONE_YEAR_SECONDS: number;
export declare const YIELD_SNAPSHOTS_DATA: string;
export declare const VAULT_BALANCES_DATA: string;
export declare const TOKEN_PRICE_DATA: string;
export declare const TOKEN_INFORMATION_DATA: string;
export declare const VAULT_SNAPSHOTS_DATA: string;
export declare const VAULT_DEFINITION_DATA: string;
export declare const REWARD_DATA: string;
export declare const LEADERBOARD_DATA: string;
export declare const ACCOUNT_DATA: string;
export declare const METRICS_SNAPSHOTS_DATA: string;
export declare const LEADERBOARD_SUMMARY_DATA: string;
export declare const UNCLAIMED_SNAPSHOTS_DATA: string;
export declare const USER_CLAIMED_METADATA: string;
export declare const YIELD_ESTIMATES_DATA: string;
export declare const HARVEST_COMPOUND_DATA: string;
export declare const PROTOCOL_DATA: string;
export declare const CHART_DATA: string;
export declare const UNISWAP_URL: string;
export declare const SUSHISWAP_URL: string;
export declare const SUSHISWAP_MATIC_URL: string;
export declare const SUSHISWAP_ARBITRUM_URL: string;
export declare const PANCAKESWAP_URL: string;
export declare const QUICKSWAP_URL: string;
export declare const SWAPR_URL: string;
export declare const BALANCER_URL: string;
export declare const STAGE: string;
export declare const API_VERSION = "v2.0.0";
export declare const PRODUCTION: boolean;
export declare const DISCORD_WEBHOOK_URL: string;
export declare const DEFAULT_PAGE_SIZE = 20;
export declare const swaggerConfig: SwaggerSettings;
