name: Deploy

on:
  pull_request:
    types: [ closed ]
    branches: [ main, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Deploy Staging
        uses: serverless/github-action@master
        with:
          args: deploy
        if: contains(github.ref, 'staging')
      - name: Deploy Production
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        if: contains(github.ref, 'main')

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
  ETH_RPC: ${{ secrets.ETH_RPC }}
  BSC_RPC: ${{ secrets.BSC_RPC }}
  MATIC_RPC: ${{ secrets.MATIC_RPC }}
  ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  ARBISCAN_API_KEY: ${{ secrets.ARBISCAN_API_KEY }}
