name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
      name: deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: yarn install --frozen-lockfile
        - run: npm install -g serverless
        - run: sls config credentials -p aws -k ${{ secrets.AWS_ACCESS_KEY_ID }} -s ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - run: sls decrypt --stage prod --password ${{ secrets.SECRETS_PASSWORD }}
        - run: sls deploy --stage prod
        - run: sls downloadDocumentation --outputFileName="src/swagger/swagger.json"
        - run: npx ts-node src/swagger/sanitize.ts
