name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
      name: deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: yarn install --frozen-lockfile
        - name: serverless decrypt secrets
          uses: serverless/github-action@master
          with:
            args: -c "sls plugin install --name serverless-secrets-plugin && sls decrypt --stage prod --password ${{ secrets.SECRETS_PASSWORD }}"
            entrypoint: /bin/bash
        - name: serverless deploy
          uses: serverless/github-action@master
          with:
            args: deploy --stage prod
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: serverless download documentation
          uses: serverless/github-action@master
          with:
            args: downloadDocumentation --outputFileName=swagger/swagger.json
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: sanitize documentation
          run: npx ts-code src/swagger/sanitize.js
