name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
      name: deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Deploy + Upload Documentation
          run: |
            yarn
            sls deploy --stage prod
            sls downloadDocumentation --outputFileName=swagger/swagger.json
            npx ts-code src/swagger/sanitize.js
